apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: kafka-deployment-1
  namespace: data-stream
spec: 
  serviceName: kafka1
  replicas: 1
  selector: 
    matchLabels:
      app: kafka-broker-1
  template:
    metadata: 
      labels: 
        app: kafka-broker-1
    spec:
      nodeSelector:
        nodeType: memory-local-docker
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "localhost"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_CREATE_TOPICS
          value: "test-topic"
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "5555"
        - name: KAFKA_CLEANUP_POLICY
          value: "compact"
        volumeMounts:
          - name: local-kafka-volume
            mountPath: "/kafka/kafka-logs"
      volumes:
        - name: local-kafka-volume
          hostPath:
            path: /Users/xiaoxiaosu/Documents/Codes/GitHub/K8S/mountedVolume/kafka/broker1