apiVersion: v1
kind: Service
metadata: 
  name: kafka1
  namespace: data-stream
  labels: 
    app: kafka-broker-1
spec: 
  ports: 
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-broker-1
  type: LoadBalancer